[package]
name = "makedot_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
pest = "2.5"
pest_derive = "2.5"
petgraph = "0.7"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.3"
