version = 1

[install]
cargo.pkg-path = "cargo"
rustc.pkg-path = "rustc"
clang.pkg-path = "clang"
graphviz.pkg-path = "graphviz"

[build.makedot-rs]
sandbox = "off"
command = """
  cargo build --release
  mkdir -p $out/bin
  cp target/release/makedot-rs $out/bin
"""
